server:
  port: 80
  servlet:
    session:
      tracking-modes: cookie

spring:
  application:
    name: ShopZone
  datasource:
    url: jdbc:mysql://192.168.219.100:5036/ShopZone
    username: ShopZone
    password: ShopZone1234
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 3
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis:
  mapper-locations: classpath:mybatis/mapper/**/**.xml